version: "3.9"

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"

  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
    volumes:
      - ../backend/app:/app/app
      - ../llm:/project/llm

  ollama:
    ports:
      - "11434:11434"

  redis:
    ports:
      - "6379:6379"

  postgres:
    ports:
      - "5432:5432"
